<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="OpenMCSEmodelingFun" nsURI="http://ietr-ensta/OpenMCSEmodeling/0.2"
    nsPrefix="mcseFun">
  <eClassifiers xsi:type="ecore:EClass" name="ModelMCSE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//Relations" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Modstructure" upperBound="-1"
        eType="#//Structure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Moddevices" upperBound="-1"
        eType="#//Device" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Modconnection" upperBound="-1"
        eType="#//Connection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Moddatatype" upperBound="-1"
        eType="#//DataType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Safety" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="100 %"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EventPolicyEnum">
    <eLiterals name="Boolean"/>
    <eLiterals name="Counter"/>
    <eLiterals name="Fugitive"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relations" abstract="true" eSuperTypes="#//FromTo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changedDirection" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DuringTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BeginTimePoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EndTimePoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Safety" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="100 %"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Structure" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Strport" upperBound="-1"
        eType="#//Port" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="SystemC"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Blackbox" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BeginTimePoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EndTimePoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DuringTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Safety" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="100 %"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ValidationTarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="N/A"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behavior" abstract="true" eSuperTypes="#//FromTo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Appearance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Attributes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DuringTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BeginTimePoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EndTimePoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Safety" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="100 %"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changedDirection" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Devport" upperBound="-1"
        eType="#//Port" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DuringTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BeginTimePoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EndTimePoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Safety" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="100 %"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Templates" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templates" upperBound="-1"
        eType="#//ModelMCSE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageQueue" eSuperTypes="#//Relations #//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="QueuePolicy" eType="#//QueuePolicyEnum"
        defaultValueLiteral="FIFOFinite"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="QueueCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Concurrency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SendTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1 ns"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReceiveTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1 ns"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SendThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReceiveThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Protocol" eType="#//ProtocolEnum"
        defaultValueLiteral="CoFluent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Response" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="N/A"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BaseAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="N/A"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AddressMask" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="N/A"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SharedVariable" eSuperTypes="#//Relations #//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Semaphore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Concurrency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Counter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WriteTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1 ns"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReadTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1 ns"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//Relations">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EventPolicy" eType="#//EventPolicyEnum"
        defaultValueLiteral="Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SetTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1 ns"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GetTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1 ns"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodCallInterface" eSuperTypes="#//Relations"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClockGenerator" eSuperTypes="#//Structure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ClockPeriod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1 μs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ClockOffset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1 μs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ExecutionTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="10 ns"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Divider" eSuperTypes="#//Structure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DivideRatio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ExecutionTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="10 ns"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageRouting" eSuperTypes="#//Structure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Concurrency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RoutingTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="10 ns"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SampledFunction" eSuperTypes="#//Function #//MappedFunction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SamplingPeriod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1 μs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SamplingOffset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1 μs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemCIP" eSuperTypes="#//Structure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ConstructorArguments" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true" defaultValueLiteral="list of string cant use EElist"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialNode" eSuperTypes="#//Behavior">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFirst" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//Behavior">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Algorithm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ExecutionTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="10 ns"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SystematicRead" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SystematicWrite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AbortEvent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="type of Event Input"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DynamicDataSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0 kB"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DynamicPowerConsumption"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="0 uW"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LoadType" eType="#//LoadTypeEnum"
        defaultValueLiteral="Active"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DynamicResourceLoad" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="N/A"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//Behavior">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="#//TypeEnum"
        defaultValueLiteral="Infinite"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeEnum">
    <eLiterals name="Infinite"/>
    <eLiterals name="Division"/>
    <eLiterals name="Conditional"/>
    <eLiterals name="Multiplication"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LoadTypeEnum">
    <eLiterals name="Active"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputAction" eSuperTypes="#//Behavior">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReceiveTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="null"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Timeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="null"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="null"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VectorSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Blocking" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Broadcast" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReadTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="null"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GetTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="null"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SendTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="null"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputAction" eSuperTypes="#//Behavior">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WriteTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="null"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SetTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="null"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alternative" eSuperTypes="#//Behavior"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleWait" eSuperTypes="#//Behavior"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultiInputSelector" eSuperTypes="#//Behavior"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultiOutputSelector" eSuperTypes="#//Behavior"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceProgrammersView" eSuperTypes="#//Device"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectedInterface" eSuperTypes="#//Device"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImplementedInterface" eSuperTypes="#//Device"/>
  <eClassifiers xsi:type="ecore:EClass" name="Producer" eSuperTypes="#//Templates"/>
  <eClassifiers xsi:type="ecore:EClass" name="Consumer" eSuperTypes="#//Templates"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessingFunction" eSuperTypes="#//Templates"/>
  <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//FromTo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Safety" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="100 %"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FromTo" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="last" upperBound="-1" eType="#//FromTo"
        eOpposite="#//FromTo/next"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" upperBound="-1" eType="#//FromTo"
        eOpposite="#//FromTo/last"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Confrom" lowerBound="1"
        upperBound="-1" eType="#//FromTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Conto" lowerBound="1" upperBound="-1"
        eType="#//FromTo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//Structure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBehaviorFunction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Funbehavior" upperBound="-1"
        eType="#//Behavior" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subFunction" upperBound="-1"
        eType="#//Function" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Fundevices" upperBound="-1"
        eType="#//Device" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Funrelations" upperBound="-1"
        eType="#//Relations" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CyclePeriod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="null"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Scope" eType="#//ScopeEnum"
        defaultValueLiteral="System"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dynamic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DoNotStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predefini" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ExternallyDefined" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Initialization" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Vardatatype" lowerBound="1"
        eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappedFunction" eSuperTypes="#//Function">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Affinity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StaticCodeSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0 kByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StaticDataSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0 kByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StaticPowerConsumption"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="0 μW"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DynamicPowerConsumption"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="0 μW"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1 USD"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DynamicResourceLoad" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="100 %"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScopeEnum">
    <eLiterals name="System"/>
    <eLiterals name="Environment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="QueuePolicyEnum">
    <eLiterals name="FIFOFinite"/>
    <eLiterals name="Priority"/>
    <eLiterals name="Fugitive"/>
    <eLiterals name="FIFOInfinite"/>
    <eLiterals name="RendezVous"/>
    <eLiterals name="Multirate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProtocolEnum">
    <eLiterals name="CoFluent"/>
  </eClassifiers>
</ecore:EPackage>
